# These are supported funding model platforms

# GitHub Sponsors
# github: [Rahulladumor]

# Open Collective
# open_collective: your-username

# Ko-fi
# ko_fi: your-username

# Buy Me a Coffee
# custom: ['https://www.buymeacoffee.com/your-username']

# Patreon
# patreon: your-username

# Custom funding links
custom:
  - 'https://topmate.io/rahulladumor'
  - 'https://www.linkedin.com/in/rahulladumor/'
